FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:244 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x800421329d 0x8004209ec0 0x8004219702 0x80042071ac
Translation of call stack:
0x000000800421329d: debug_panic (lib/kernel/debug.c:32)
0x0000008004209ec0: lock_release (threads/synch.c:247)
0x0000008004219702: donor_thread_func (tests/threads/priority-donate-chain.c:104)
0x00000080042071ac: kernel_thread (threads/thread.c:399)
